[project]
name = "edgartools-wrapper"
version = "0.1.0"
description = "Wrapper for edgartools via Nix"
requires-python = ">=3.12"
dependencies = [
    "edgartools==4.8.2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["edgartools_wrapper"]