name: cloudflare-deployment
runtime:
  name: nodejs
  options:
    typescript: true
description: Cloudflare deployment management using Pulumi TypeScript
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-east-1