name: Self-hosted Runner Cowsay Test

on:
  push:
    paths:
      - 'src/poc/gha-self/**'

jobs:
  cowsay-self-hosted:
    runs-on: [self-hosted, nix, flake-gha-self]
    steps:
      - name: Run cowsay
        run: |
          nix run nixpkgs#cowsay -- "POC: Self-hosted runner works! ğŸ®"