name = "react-transition-demo"
main = "src/worker.tsx"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/assets"
binding = "ASSETS"

[env.production]
name = "react-transition-demo"