name = "shiorin-diary-prod"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "src/worker.ts"

[observability]
enabled = true

[dev]
port = 8787

[env.staging]
name = "shiorin-diary-stg"

[[env.staging.kv_namespaces]]
binding = "CACHE"
# Create KV and set the ID here: `wrangler kv namespace create shiorin-diary-stg-cache`
id = "0039133a4d9e42d8be37f7e435f6a457"

[[env.staging.r2_buckets]]
binding = "FILES_BUCKET"
# Create R2 bucket from dashboard or CLI and set the name below
bucket_name = "stg-shiorin-diary-files"

