[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "persistence-kuzu"
version = "0.1.0"
description = "Persistence layer with customized KuzuDB"
dependencies = [
    "numpy",
    "pandas",
    "pydantic",
]